"""empty message

Revision ID: eb502f4ad33c
Revises: 
Create Date: 2021-11-23 16:59:13.298050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb502f4ad33c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bird_sound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('annontate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.Column('date', sa.String(length=150), nullable=True),
    sa.Column('audio_name', sa.String(length=150), nullable=True),
    sa.Column('user_email', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annontate')
    op.drop_table('user')
    op.drop_table('bird_sound')
    # ### end Alembic commands ###
